apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  apikey: ODY2MWZiMjRhY2I2ODU1NTBmNWQ4OTBlNDQwZDM2MWFiYThmODY2N2NhZDNhMTMzOGJkZWNjNTViMWU2ZDNiYmRhNGU3YmQxMzMxZGFmMGFlYmU5MDA1ZDE5OWQxZWY1
  