# mongodb-storage.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    types: local
    app: mongodb
spec:
  capacity:
    storage: 2Gi
#  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: mongodb-storage
  hostPath:
    path: /data/mongodb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: mongodb-storage
  resources:
    requests:
      storage: 2Gi
