# admin-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
#  namespace: my-namespace
  name: admin-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "deletecollection", "patch", "delete", "create", "update"]
