 kind: NetworkPolicy
 apiVersion: networking.k8s.io/v1
 metadata:
  name: backend-ingress
 spec:
  podSelector:
    matchLabels:
      app: backend
      role: admin-role
  ingress:
  - from:
      - podSelector:
          matchLabels:
            app: mongodb