# rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: app-role-binding
subjects:
- kind: ServiceAccount
  name: admin-service-account
roleRef:
  kind: Role
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
