apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: {{ .Values.frontend.image }}
        env:
        - name: SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: server-address
              key: SERVER_URL
        ports:
        - containerPort: {{ .Values.frontend.port }}
      imagePullSecrets:
      - name:  webapp-registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30100
