# viewer-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  #  namespace: my-namespace
  name: reader-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "services", "configmaps", "deployments" ]
    verbs: [ "get", "list", "watch" ]
